version: '3.6.9'

services:

  db_beautify:
    container_name: db_beautify
    image: postgres:15.0
    restart: always
    volumes:
      - ./dbdata:/var/lib/postgresql/data
    ports:
      - '${DB_PORT}:${DB_PORT}'
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}

  api_beautify:
    container_name: api_beautify
    restart: always
    build:
      context: ./api
      dockerfile: Dockerfile
    volumes:
      - /api/node_modules
      - ./api:/api
    depends_on:
      db_beautify:
        condition: service_healthy
    stdin_open: true
    environment:
      PORT: ${API_PORT}
      WATCHPACK_POLLING: true
    ports:
      - '${API_PORT}:${API_PORT}'

  web_beautify:
    container_name: web_beautify
    build:
      context: ./web
      dockerfile: Dockerfile
    volumes:
      - /web/node_modules
      - ./web:/web
    depends_on:
      - api_beautify
    stdin_open: true
    environment:
      - WATCHPACK_POLLING=true
    ports:  
      - '${WEB_PORT}:${WEB_PORT}'