version: '3.6.9'

services:

  db_beautify:
    container_name: db_beautify
    image: postgres:15.0
    restart: always
    volumes:
      - ./dbdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}

  # api_beautify:
  #   container_name: api_beautify
  #   build:
  #     context: ./api
  #     dockerfile: Dockerfile
  #   volumes:
  #     - ./api:/api
  #   depends_on:
  #     db_hub:
  #       condition: service_healthy
  #   environment:
  #     DATABASE_URL: ${DATABASE_URL}
  #     PORT: ${API_PORT}
  #   ports:
  #     - '8001:${API_PORT}'

  # web_beautify:
  #   container_name: web_beautify
  #   build:
  #     context: ./web
  #     dockerfile: Dockerfile
  #   volumes:
  #     - /web/node_modules
  #     - ./web:/web
  #   depends_on:
  #     - api_beautify
  #   stdin_open: true
  #   environment:
  #     - WATCHPACK_POLLING=true
  #   ports:  
  #   - '8090:8080'