version: 2.1
orbs:
  heroku: circleci/heroku@1.2.6
jobs:
  build:
    docker:
      - image: cimg/php:8.1-browsers

    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "composer.json" }}
      - run:
          name: "Install Composer Dependencies"
          command: composer install -n --prefer-dist
      - run:
          name: "Install Node Dependencies"
          command: npm install -n --prefer-dist
      - run:
          name: "Run Node Dependencies"
          command: npm run build
      - save_cache:
          key: v1-dependencies-{{ checksum "composer.json" }}
          paths:
            - ./vendor
  deploy_app:
    executor: heroku/default
    steps:
      - checkout
      - heroku/install
      - heroku/deploy-via-git:
          force: true
      - run:
          command: |
            heroku run --app=${HEROKU_APP_NAME} php artisan storage:link
workflows:
  deploy:
    jobs:
      - build
      - deploy_app
